name: Run E2E Test

on:
 workflow_run:
   workflows:
     - "Deploy to Staging"
   types:
     - completed

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Use Node 20
       uses: actions/setup-node@v4
       with:
         node-version: 20.x

     - name: Install Playwright dependencies
       run: npx playwright install-deps
       working-directory: ./e2e

     - name: Setup E2E test
       run: npm ci
       working-directory: ./e2e


     - name: Run E2E test
       run: npm run test
       working-directory: ./e2e
       env:
        BASE_URL: 'https://testautomation2-staging.up.railway.app'
        HEADLESS: true

     - name: Load test repository history
       uses: actions/checkout@v4
       if: always()
       with: 
         ref: gh-pages
         path: gh-pages

     - name: Build test report
       uses: peaceiris/actions/gh-pages@v4
       if: always()
       with: 
         github_token: ${{ secrets.GITHUB_TOKEN}}
         publish_branch: gh-pages
         publish_dir: allure-history